### ISSUE TITLE
Cant start HuGu

### ISSUE THREAD

**Issue by isaeff** [antirek/hugu#4]
npm start

> HuGu@0.0.2 start /home/web25/hugu
> node app.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Function.app.listen (/home/web25/hugu/node_modules/express/lib/application.js:534:24)
    at Object.<anonymous> (/home/web25/hugu/app.js:38:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! HuGu@0.0.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the HuGu@0.0.2 start script.
npm ERR! This is most likely a problem with the HuGu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls HuGu
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-39-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/web25/hugu
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/web25/hugu/npm-debug.log
npm ERR! not ok code 0

**Comment by antirek** [comment]
hugu use ports 80, 3001
if  you use this ports in your other apps, change in hugu app.js strings:
app.set('port_http', 80);
app.set('port_websocket', 3001);

**Comment by isaeff** [comment]
I changed this stings, but result is te same.

**Comment by antirek** [comment]
Oh, try run 'sudo npm start'. (May be required additional access).

I try under user and have error too.
````
sergey@sergey-R410P:~/Projects/hugu$ npm start

> HuGu@0.0.2 start /home/sergey/Projects/hugu
> node app.js

   info  - socket.io started

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Function.app.listen (/home/sergey/Projects/hugu/node_modules/express/lib/application.js:534:24)
    at Object.<anonymous> (/home/sergey/Projects/hugu/app.js:38:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! HuGu@0.0.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the HuGu@0.0.2 start script.
npm ERR! This is most likely a problem with the HuGu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls HuGu
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/sergey/Projects/hugu
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/sergey/Projects/hugu
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sergey/Projects/hugu/npm-debug.log
npm ERR! not ok code 0
sergey@sergey-R410P:~/Projects/hugu$ sudo npm start

> HuGu@0.0.2 start /home/sergey/Projects/hugu
> node app.js

   info  - socket.io started
Express server listening on port 81
WebSockets server listening on port 3001

````

**Comment by isaeff** [comment]
thx! it helped :)
